# SHS-Thesis-Statistician

In [ ]:
#Import Libraries
import pandas as pd
import numpy as np
from scipy.stats import spearmanr, shapiro

## Data Preparation

In [3]:
#Import Data
file1 = pd.read_csv("DemographicProfile.csv")
file2 = pd.read_csv("GWA.csv")
file3 = pd.read_csv("LikertScale.csv")

In [4]:
#Data Cleaning
file1_clean = file1.iloc[:, :4]
file2_clean = file2.iloc[:, :3]
file3_clean = file3.dropna(axis=1, how='all')

In [5]:
#Check Cleaned Data
print(file1_clean.head())
print(file2_clean.head())
print(file3_clean.head())

   RESPONDENTS  AGE  SEX  STRAND
0            1    2    2       1
1            2    2    1       1
2            3    2    2       1
3            4    2    2       1
4            5    2    2       1
   RESPONDENTS  WA  GWA
0            1   4    3
1            2   4    3
2            3   2    2
3            4   4    4
4            5   1    7
   RESPONDENTS  Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  ...  Q11  Q12  Q13  Q14  \
0            1   3   2   3   4   5   4   5   5   5  ...    3    3    5    4
1            2   2   5   3   5   5   3   4   1   5  ...    1    2    5    4
2            3   3   2   3   2   4   5   4   5   5  ...    3    3    5    4
3            4   2   3   4   3   3   3   3   2   4  ...    2    3    3    4
4            5   5   5   4   3   5   4   4   4   5  ...    5    5    3    4

   Q15  Q16  Q17  Q18  Q19  Q20
0    5    4    2    3    2    3
1    4    5    1    2    1    1
2    4    3    3    4    3    4
3    4    3    1    2    2    2
4    4    3    5    5    5    5

[5 rows x 21 columns]

## Demographic Profile Outputs

In [6]:
#Age
age_labels = {
    1: "16-17",
    2: "18+"
}
freqAge = file1_clean["AGE"].value_counts().sort_index()
percentAge = (freqAge / freqAge.sum()) * 100
table_age = pd.DataFrame({
    "Age": [age_labels[i] for i in freqAge.index],
    "Code": freqAge.index,
    "Frequency": freqAge.values,
    "Percentage": percentAge.round(2).values
})
table_age.loc[len(table_age)] = ["Total", "", freqAge.sum(), 100]

table_age

     Age Code  Frequency  Percentage
0  16-17    1         97       52.15
1    18+    2         89       47.85
2  Total             186      100.00

In [7]:
#Sex
sex_labels = {
    1: "Male",
    2: "Female"
}
freqSex = file1_clean["SEX"].value_counts().sort_index()
percentSex = (freqSex / freqSex.sum()) * 100
table_sex = pd.DataFrame({
    "Sex": [sex_labels[i] for i in freqSex.index],
    "Code": freqSex.index,
    "Frequency": freqSex.values,
    "Percentage": percentSex.round(2).values
})
table_sex.loc[len(table_age)] = ["Total", "", freqSex.sum(), 100]

table_sex

      Sex Code  Frequency  Percentage
0    Male    1         89       47.85
1  Female    2         97       52.15
3   Total             186      100.00

In [8]:
#Strand
strand_labels = {
    1: "ABM",
    2: "HUMSS",
    3: "HE",
    4: "ICT",
    5: "SMAW"
}

freqStrand = file1_clean["STRAND"].value_counts().sort_index()
percentStrand = (freqStrand / freqStrand.sum()) * 100

table_strand = pd.DataFrame({
    "Strand": [strand_labels[i] for i in freqStrand.index],
    "Code": freqStrand.index,
    "Frequency": freqStrand.values,
    "Percentage": percentStrand.round(2).values
})

table_strand.loc[len(table_strand)] = ["Total", "", freqStrand.sum(), 100]

table_strand

  Strand Code  Frequency  Percentage
0    ABM    1         17        9.14
1  HUMSS    2         49       26.34
2     HE    3         25       13.44
3    ICT    4         25       13.44
4   SMAW    5         70       37.63
5  Total             186      100.00

## GWA Outputs

In [9]:
#WA
wa_labels = {
    1: "ABOVE 500",
    2: "401-500",
    3: "301-400",
    4: "201-300",
    5: "101-200",
    6: "BELOW 100"
}

freqWA = file2_clean["WA"].value_counts().sort_index()
percentWA = (freqWA / freqWA.sum()) * 100

table_WA = pd.DataFrame({
    "WA": [wa_labels[i] for i in freqWA.index],
    "Code": freqWA.index,
    "Frequency": freqWA.values,
    "Percentage": percentWA.round(2).values
})

table_WA.loc[len(table_WA)] = ["Total", "", freqWA.sum(), 100]

print(table_WA)

mean_WA = file2_clean["WA"].mean()
median_WA = file2_clean["WA"].median()
mode_WA = file2_clean["WA"].mode()[0]

print("\nMean:", round(mean_WA,2))
print("Median:", median_WA)
print("Mode:", mode_WA)

          WA Code  Frequency  Percentage
0  ABOVE 500    1         27       14.52
1    401-500    2         21       11.29
2    301-400    3          7        3.76
3    201-300    4         27       14.52
4    101-200    5         29       15.59
5  BELOW 100    6         75       40.32
6      Total             186      100.00

Mean: 4.26
Median: 5.0
Mode: 6

In [10]:
# 1. Map labels
gwa_labels = {1: "98-100",
    2: "95-97",
    3: "90-94", 
    4: "85-89", 
    5: "80-84", 
    6: "75-79", 
    7: "BELOW 75"
}

freqGWA = file2_clean["GWA"].value_counts().reindex(gwa_labels.keys(), fill_value=0)
percentGWA = (freqGWA / freqGWA.sum()) * 100

table_gwa = pd.DataFrame({
    "GWA": [gwa_labels[i] for i in freqGWA.index],
    "Code": freqGWA.index,
    "Frequency": freqGWA.values,
    "Percentage": percentGWA.round(2).values
})

table_gwa.loc[len(table_gwa)] = ["Total", "", freqGWA.sum(), 100]

print(table_gwa)

mean_GWA = file2_clean["GWA"].mean()
median_GWA = file2_clean["GWA"].median()
mode_GWA = file2_clean["GWA"].mode()[0]

print("\nMean:", round(mean_GWA, 2))
print("Median:", median_GWA)
print("Mode:", mode_GWA)

        GWA Code  Frequency  Percentage
0    98-100    1          0        0.00
1     95-97    2         10        5.38
2     90-94    3         83       44.62
3     85-89    4         68       36.56
4     80-84    5         21       11.29
5     75-79    6          3        1.61
6  BELOW 75    7          1        0.54
7     Total             186      100.00

Mean: 3.61
Median: 3.5
Mode: 3

## Likert Scale Outputs

In [11]:
import pandas as pd

likert_labels = {1: "SD", 2: "D", 3: "N", 4: "A", 5: "SA"}

def get_likert_results(column_data):
    freq = column_data.value_counts().reindex(likert_labels.keys(), fill_value=0)
    percent = (freq / freq.sum()) * 100
    
    df = pd.DataFrame({
        "Scale": [likert_labels[i] for i in freq.index],
        "Code": freq.index,
        "Frequency": freq.values,
        "Percentage": percent.round(2).values
    })
    df.loc[len(df)] = ["Total", "", freq.sum(), 100]
    return df

def print_stats(column_data, label):
    print(f"--- {label} Statistics ---")
    print(f"Mean: {round(column_data.mean(), 2)}")
    print(f"Median: {column_data.median()}")
    print(f"Mode: {column_data.mode()[0]} \n")

In [12]:
table_Q1 = get_likert_results(file3_clean["Q1"])
print("Q1 Table:")
print(table_Q1)
print_stats(file3_clean["Q1"], "Q1")

table_Q2 = get_likert_results(file3_clean["Q2"])
print("\nQ2 Table:")
print(table_Q2)
print_stats(file3_clean["Q2"], "Q2")

table_Q3 = get_likert_results(file3_clean["Q3"])
print("\nQ3 Table:")
print(table_Q3)
print_stats(file3_clean["Q3"], "Q3")

table_Q4 = get_likert_results(file3_clean["Q4"])
print("\nQ4 Table:")
print(table_Q4)
print_stats(file3_clean["Q4"], "Q4")

table_Q5 = get_likert_results(file3_clean["Q5"])
print("\nQ5 Table:")
print(table_Q5)
print_stats(file3_clean["Q5"], "Q5")

table_Q6 = get_likert_results(file3_clean["Q6"])
print("\nQ6 Table:")
print(table_Q6)
print_stats(file3_clean["Q6"], "Q6")

table_Q7 = get_likert_results(file3_clean["Q7"])
print("\nQ7 Table:")
print(table_Q7)
print_stats(file3_clean["Q7"], "Q7")

table_Q8 = get_likert_results(file3_clean["Q8"])
print("\nQ8 Table:")
print(table_Q8)
print_stats(file3_clean["Q8"], "Q8")

table_Q9 = get_likert_results(file3_clean["Q9"])
print("\nQ9 Table:")
print(table_Q9)
print_stats(file3_clean["Q9"], "Q9")

table_Q10 = get_likert_results(file3_clean["Q10"])
print("\nQ10 Table:")
print(table_Q10)
print_stats(file3_clean["Q10"], "Q10")

table_Q11 = get_likert_results(file3_clean["Q11"])
print("\nQ11 Table:")
print(table_Q11)
print_stats(file3_clean["Q11"], "Q11")

table_Q12 = get_likert_results(file3_clean["Q12"])
print("\nQ12 Table:")
print(table_Q12)
print_stats(file3_clean["Q12"], "Q12")

table_Q13 = get_likert_results(file3_clean["Q13"])
print("\nQ13 Table:")
print(table_Q13)
print_stats(file3_clean["Q13"], "Q13")

table_Q14 = get_likert_results(file3_clean["Q14"])
print("\nQ14 Table:")
print(table_Q14)
print_stats(file3_clean["Q14"], "Q14")

table_Q15 = get_likert_results(file3_clean["Q15"])
print("\nQ15 Table:")
print(table_Q15)
print_stats(file3_clean["Q15"], "Q15")

table_Q16 = get_likert_results(file3_clean["Q16"])
print("\nQ16 Table:")
print(table_Q16)
print_stats(file3_clean["Q16"], "Q16")

table_Q17 = get_likert_results(file3_clean["Q17"])
print("\nQ17 Table:")
print(table_Q17)
print_stats(file3_clean["Q17"], "Q17")

table_Q18 = get_likert_results(file3_clean["Q18"])
print("\nQ18 Table:")
print(table_Q18)
print_stats(file3_clean["Q18"], "Q18")

table_Q19 = get_likert_results(file3_clean["Q19"])
print("\nQ19 Table:")
print(table_Q19)
print_stats(file3_clean["Q19"], "Q19")

table_Q20 = get_likert_results(file3_clean["Q20"])
print("\nQ20 Table:")
print(table_Q20)
print_stats(file3_clean["Q20"], "Q20")

Q1 Table:
   Scale Code  Frequency  Percentage
0     SD    1         20       10.75
1      D    2         35       18.82
2      N    3         55       29.57
3      A    4         55       29.57
4     SA    5         21       11.29
5  Total             186      100.00
--- Q1 Statistics ---
Mean: 3.12
Median: 3.0
Mode: 3


Q2 Table:
   Scale Code  Frequency  Percentage
0     SD    1         22       11.83
1      D    2         55       29.57
2      N    3         41       22.04
3      A    4         39       20.97
4     SA    5         29       15.59
5  Total             186      100.00
--- Q2 Statistics ---
Mean: 2.99
Median: 3.0
Mode: 2


Q3 Table:
   Scale Code  Frequency  Percentage
0     SD    1         19       10.22
1      D    2         17        9.14
2      N    3         47       25.27
3      A    4         69       37.10
4     SA    5         34       18.28
5  Total             186      100.00
--- Q3 Statistics ---
Mean: 3.44
Median: 4.0
Mode: 4


Q4 Table:
   Scale Code  Frequency  Percentage
0     SD    1         18        9.68
1      D    2         15        8.06
2      N    3         62       33.33
3      A    4         64       34.41
4     SA    5         27       14.52
5  Total             186      100.00
--- Q4 Statistics ---
Mean: 3.36
Median: 3.0
Mode: 4


Q5 Table:
   Scale Code  Frequency  Percentage
0     SD    1         23       12.37
1      D    2          9        4.84
2      N    3         47       25.27
3      A    4         53       28.49
4     SA    5         54       29.03
5  Total             186      100.00
--- Q5 Statistics ---
Mean: 3.57
Median: 4.0
Mode: 5


Q6 Table:
   Scale Code  Frequency  Percentage
0     SD    1          8        4.30
1      D    2         17        9.14
2      N    3         57       30.65
3      A    4         64       34.41
4     SA    5         40       21.51
5  Total             186      100.00
--- Q6 Statistics ---
Mean: 3.6
Median: 4.0
Mode: 4


Q7 Table:
   Scale Code  Frequency  Percentage
0     SD    1         10        5.38
1      D    2         26       13.98
2      N    3         58       31.18
3      A    4         63       33.87
4     SA    5         29       15.59
5  Total             186      100.00
--- Q7 Statistics ---
Mean: 3.4
Median: 3.0
Mode: 4


Q8 Table:
   Scale Code  Frequency  Percentage
0     SD    1         19       10.22
1      D    2         31       16.67
2      N    3         55       29.57
3      A    4         48       25.81
4     SA    5         33       17.74
5  Total             186      100.00
--- Q8 Statistics ---
Mean: 3.24
Median: 3.0
Mode: 3


Q9 Table:
   Scale Code  Frequency  Percentage
0     SD    1         17        9.14
1      D    2         20       10.75
2      N    3         44       23.66
3      A    4         57       30.65
4     SA    5         48       25.81
5  Total             186      100.00
--- Q9 Statistics ---
Mean: 3.53
Median: 4.0
Mode: 4


Q10 Table:
   Scale Code  Frequency  Percentage
0     SD    1         17        9.14
1      D    2         30       16.13
2      N    3         44       23.66
3      A    4         63       33.87
4     SA    5         32       17.20
5  Total             186      100.00
--- Q10 Statistics ---
Mean: 3.34
Median: 4.0
Mode: 4


Q11 Table:
   Scale Code  Frequency  Percentage
0     SD    1         31       16.67
1      D    2         44       23.66
2      N    3         49       26.34
3      A    4         34       18.28
4     SA    5         28       15.05
5  Total             186      100.00
--- Q11 Statistics ---
Mean: 2.91
Median: 3.0
Mode: 3


Q12 Table:
   Scale Code  Frequency  Percentage
0     SD    1         24       12.90
1      D    2         38       20.43
2      N    3         54       29.03
3      A    4         41       22.04
4     SA    5         29       15.59
5  Total             186      100.00
--- Q12 Statistics ---
Mean: 3.07
Median: 3.0
Mode: 3


Q13 Table:
   Scale Code  Frequency  Percentage
0     SD    1          8        4.30
1      D    2         14        7.53
2      N    3         29       15.59
3      A    4         73       39.25
4     SA    5         62       33.33
5  Total             186      100.00
--- Q13 Statistics ---
Mean: 3.9
Median: 4.0
Mode: 4


Q14 Table:
   Scale Code  Frequency  Percentage
0     SD    1         11        5.91
1      D    2         11        5.91
2      N    3         48       25.81
3      A    4         80       43.01
4     SA    5         36       19.35
5  Total             186      100.00
--- Q14 Statistics ---
Mean: 3.64
Median: 4.0
Mode: 4


Q15 Table:
   Scale Code  Frequency  Percentage
0     SD    1          7        3.76
1      D    2         15        8.06
2      N    3         54       29.03
3      A    4         73       39.25
4     SA    5         37       19.89
5  Total             186      100.00
--- Q15 Statistics ---
Mean: 3.63
Median: 4.0
Mode: 4


Q16 Table:
   Scale Code  Frequency  Percentage
0     SD    1          9        4.84
1      D    2         15        8.06
2      N    3         36       19.35
3      A    4         81       43.55
4     SA    5         45       24.19
5  Total             186      100.00
--- Q16 Statistics ---
Mean: 3.74
Median: 4.0
Mode: 4


Q17 Table:
   Scale Code  Frequency  Percentage
0     SD    1         33       17.74
1      D    2         57       30.65
2      N    3         35       18.82
3      A    4         40       21.51
4     SA    5         21       11.29
5  Total             186      100.00
--- Q17 Statistics ---
Mean: 2.78
Median: 3.0
Mode: 2


Q18 Table:
   Scale Code  Frequency  Percentage
0     SD    1         18        9.68
1      D    2         45       24.19
2      N    3         49       26.34
3      A    4         44       23.66
4     SA    5         30       16.13
5  Total             186      100.00
--- Q18 Statistics ---
Mean: 3.12
Median: 3.0
Mode: 3


Q19 Table:
   Scale Code  Frequency  Percentage
0     SD    1         27       14.52
1      D    2         52       27.96
2      N    3         48       25.81
3      A    4         36       19.35
4     SA    5         23       12.37
5  Total             186      100.00
--- Q19 Statistics ---
Mean: 2.87
Median: 3.0
Mode: 2


Q20 Table:
   Scale Code  Frequency  Percentage
0     SD    1         21       11.29
1      D    2         38       20.43
2      N    3         44       23.66
3      A    4         41       22.04
4     SA    5         42       22.58
5  Total             186      100.00
--- Q20 Statistics ---
Mean: 3.24
Median: 3.0
Mode: 3

In [13]:
q1_q4_combined = file3_clean[["Q1", "Q2", "Q3", "Q4"]].stack()
table_Q1_Q4 = get_likert_results(q1_q4_combined)
print("Combined Q1-Q4 Table:")
print(table_Q1_Q4)
print_stats(q1_q4_combined, "Q1-Q4 Combined")

q5_q8_combined = file3_clean[["Q5", "Q6", "Q7", "Q8"]].stack()
table_Q5_Q8 = get_likert_results(q5_q8_combined)
print("Combined Q5-Q8 Table:")
print(table_Q5_Q8)
print_stats(q5_q8_combined, "Q5-Q8 Combined")

q9_q12_combined = file3_clean[["Q9", "Q10", "Q11", "Q12"]].stack()
table_Q9_Q12 = get_likert_results(q9_q12_combined)
print("Combined Q9-Q12 Table:")
print(table_Q9_Q12)
print_stats(q9_q12_combined, "Q9-Q12 Combined")

q13_q16_combined = file3_clean[["Q13", "Q14", "Q15", "Q16"]].stack()
table_Q13_Q16 = get_likert_results(q13_q16_combined)
print("Combined Q13-Q16 Table:")
print(table_Q13_Q16)
print_stats(q13_q16_combined, "Q13-Q16 Combined")

q17_q20_combined = file3_clean[["Q17", "Q18", "Q19", "Q20"]].stack()
table_Q17_Q20 = get_likert_results(q17_q20_combined)
print("Combined Q17-Q20 Table:")
print(table_Q17_Q20)
print_stats(q17_q20_combined, "Q17-Q20 Combined")

Combined Q1-Q4 Table:
   Scale Code  Frequency  Percentage
0     SD    1         79       10.62
1      D    2        122       16.40
2      N    3        205       27.55
3      A    4        227       30.51
4     SA    5        111       14.92
5  Total             744      100.00
--- Q1-Q4 Combined Statistics ---
Mean: 3.23
Median: 3.0
Mode: 4

Combined Q5-Q8 Table:
   Scale Code  Frequency  Percentage
0     SD    1         60        8.06
1      D    2         83       11.16
2      N    3        217       29.17
3      A    4        228       30.65
4     SA    5        156       20.97
5  Total             744      100.00
--- Q5-Q8 Combined Statistics ---
Mean: 3.45
Median: 4.0
Mode: 4

Combined Q9-Q12 Table:
   Scale Code  Frequency  Percentage
0     SD    1         89       11.96
1      D    2        132       17.74
2      N    3        191       25.67
3      A    4        195       26.21
4     SA    5        137       18.41
5  Total             744      100.00
--- Q9-Q12 Combined Statistics ---
Mean: 3.21
Median: 3.0
Mode: 4

Combined Q13-Q16 Table:
   Scale Code  Frequency  Percentage
0     SD    1         35        4.70
1      D    2         55        7.39
2      N    3        167       22.45
3      A    4        307       41.26
4     SA    5        180       24.19
5  Total             744      100.00
--- Q13-Q16 Combined Statistics ---
Mean: 3.73
Median: 4.0
Mode: 4

Combined Q17-Q20 Table:
   Scale Code  Frequency  Percentage
0     SD    1         99       13.31
1      D    2        192       25.81
2      N    3        176       23.66
3      A    4        161       21.64
4     SA    5        116       15.59
5  Total             744      100.00
--- Q17-Q20 Combined Statistics ---
Mean: 3.0
Median: 3.0
Mode: 2

In [14]:
all_columns = [f"Q{i}" for i in range(1, 21)]
all_combined = file3_clean[all_columns].stack()

table_all = get_likert_results(all_combined)
print("Grand Total (Q1-Q20) Table:")
print(table_all)
print_stats(all_combined, "All Questions Combined")

Grand Total (Q1-Q20) Table:
   Scale Code  Frequency  Percentage
0     SD    1        362        9.73
1      D    2        584       15.70
2      N    3        956       25.70
3      A    4       1118       30.05
4     SA    5        700       18.82
5  Total            3720      100.00
--- All Questions Combined Statistics ---
Mean: 3.33
Median: 3.0
Mode: 4

## Significant Relationship of GWA and WA

In [15]:
columns = ["WA", "GWA"]

for col in columns:
    data = file2_clean[col].dropna()
    stat, p = shapiro(data)
    print(f"Shapiro-Wilk test for {col}: W={stat:.4f}, p-value={p:.4e}")
    if p > 0.05:
        print(f"{col} appears to be normally distributed.\n")
    else:
        print(f"{col} is NOT normally distributed.\n")

Shapiro-Wilk test for WA: W=0.8056, p-value=1.7964e-14
WA is NOT normally distributed.

Shapiro-Wilk test for GWA: W=0.8559, p-value=2.8084e-12
GWA is NOT normally distributed.

In [16]:
data = file2_clean[["WA", "GWA"]].dropna()

rho, p_value = spearmanr(data["WA"], data["GWA"])

print(f"Spearman Correlation Coefficient (ρ): {rho:.4f}")
print(f"P-value: {p_value:.4e}")

# Interpretation
if p_value <= 0.05:
    print("The correlation is statistically significant. Accept the Null Hypothesis.")
else:
    print("The correlation is NOT statistically significant. Reject the Null Hypothesis.")

Spearman Correlation Coefficient (ρ): 0.1503
P-value: 4.0600e-02
The correlation is statistically significant. Accept the Null Hypothesis.

In [20]:
rho = 0.1503
p_val = 0.0406
n = len(file2_clean[["WA", "GWA"]].dropna())
r_squared = rho**2
stderr = np.sqrt((1 - rho**2) / (n - 2))

print(f"Sample Size (n): {n}")
print(f"Spearman's Rho: {rho}")
print(f"P-value: {p_val}")
print(f"Coefficient of Determination (R²): {round(r_squared, 4)}")
print(f"Standard Error: {round(stderr, 4)}")

Sample Size (n): 186
Spearman's Rho: 0.1503
P-value: 0.0406
Coefficient of Determination (R²): 0.0226
Standard Error: 0.0729

In [23]:
import pandas as pd

def find_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
    return outliers, lower_bound, upper_bound

# Find outliers for WA
outliers_wa, low_wa, high_wa = find_outliers(file2_clean, "WA")
# Find outliers for GWA
outliers_gwa, low_gwa, high_gwa = find_outliers(file2_clean, "GWA")

print(f"--- WA Outlier Bounds: {low_wa} to {high_wa} ---")
print(f"Number of WA outliers: {len(outliers_wa)}")
print(outliers_wa[["WA", "GWA"]].head())

print(f"\n--- GWA Outlier Bounds: {low_gwa} to {high_gwa} ---")
print(f"Number of GWA outliers: {len(outliers_gwa)}")
print(outliers_gwa[["WA", "GWA"]].head())

--- WA Outlier Bounds: -4.0 to 12.0 ---
Number of WA outliers: 0
Empty DataFrame
Columns: [WA, GWA]
Index: []

--- GWA Outlier Bounds: 1.5 to 5.5 ---
Number of GWA outliers: 4
     WA  GWA
4     1    7
156   5    6
172   1    6
175   6    6